name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install Gradle 4.10.3
        run: |
          wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
          unzip gradle-4.10.3-bin.zip
          sudo mv gradle-4.10.3 /opt/gradle
          export PATH=$PATH:/opt/gradle/bin
          gradle -v

      - name: Build with Gradle
        run: gradle assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
